[package]
name = "roguelike_tut"
version = "0.1.0"
authors = ["propfeds"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rltk = {version = "0.8.7"}
specs = "0.20.0"
specs-derive = "0.4.1"
